# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_lp_analysis', [dirname(__file__)])
        except ImportError:
            import _lp_analysis
            return _lp_analysis
        if fp is not None:
            try:
                _mod = imp.load_module('_lp_analysis', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _lp_analysis = swig_import_helper()
    del swig_import_helper
else:
    import _lp_analysis
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


WRITE = _lp_analysis.WRITE
READ = _lp_analysis.READ
class ResourceSharingInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ResourceSharingInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ResourceSharingInfo, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _lp_analysis.new_ResourceSharingInfo(*args)
        try: self.this.append(this)
        except: self.this = this
    def add_task(self, *args): return _lp_analysis.ResourceSharingInfo_add_task(self, *args)
    def add_request(self, *args): return _lp_analysis.ResourceSharingInfo_add_request(self, *args)
    def add_request_rw(self, *args): return _lp_analysis.ResourceSharingInfo_add_request_rw(self, *args)
    __swig_destroy__ = _lp_analysis.delete_ResourceSharingInfo
    __del__ = lambda self : None;
ResourceSharingInfo_swigregister = _lp_analysis.ResourceSharingInfo_swigregister
ResourceSharingInfo_swigregister(ResourceSharingInfo)

NO_CPU = _lp_analysis.NO_CPU
class ResourceLocality(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ResourceLocality, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ResourceLocality, name)
    __repr__ = _swig_repr
    def assign_resource(self, *args): return _lp_analysis.ResourceLocality_assign_resource(self, *args)
    def __init__(self): 
        this = _lp_analysis.new_ResourceLocality()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lp_analysis.delete_ResourceLocality
    __del__ = lambda self : None;
ResourceLocality_swigregister = _lp_analysis.ResourceLocality_swigregister
ResourceLocality_swigregister(ResourceLocality)

class ReplicaInfo(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ReplicaInfo, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ReplicaInfo, name)
    __repr__ = _swig_repr
    def set_replicas(self, *args): return _lp_analysis.ReplicaInfo_set_replicas(self, *args)
    def __init__(self): 
        this = _lp_analysis.new_ReplicaInfo()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lp_analysis.delete_ReplicaInfo
    __del__ = lambda self : None;
ReplicaInfo_swigregister = _lp_analysis.ReplicaInfo_swigregister
ReplicaInfo_swigregister(ReplicaInfo)

class BlockingBounds(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlockingBounds, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BlockingBounds, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _lp_analysis.new_BlockingBounds(*args)
        try: self.this.append(this)
        except: self.this = this
    def raise_blocking_length(self, *args): return _lp_analysis.BlockingBounds_raise_blocking_length(self, *args)
    def size(self): return _lp_analysis.BlockingBounds_size(self)
    def get_blocking_term(self, *args): return _lp_analysis.BlockingBounds_get_blocking_term(self, *args)
    def get_blocking_count(self, *args): return _lp_analysis.BlockingBounds_get_blocking_count(self, *args)
    def get_span_term(self, *args): return _lp_analysis.BlockingBounds_get_span_term(self, *args)
    def get_span_count(self, *args): return _lp_analysis.BlockingBounds_get_span_count(self, *args)
    def get_raw_remote_blocking(self, *args): return _lp_analysis.BlockingBounds_get_raw_remote_blocking(self, *args)
    def get_remote_blocking(self, *args): return _lp_analysis.BlockingBounds_get_remote_blocking(self, *args)
    def get_remote_count(self, *args): return _lp_analysis.BlockingBounds_get_remote_count(self, *args)
    def set_remote_blocking(self, *args): return _lp_analysis.BlockingBounds_set_remote_blocking(self, *args)
    def get_local_blocking(self, *args): return _lp_analysis.BlockingBounds_get_local_blocking(self, *args)
    def get_local_count(self, *args): return _lp_analysis.BlockingBounds_get_local_count(self, *args)
    def set_local_blocking(self, *args): return _lp_analysis.BlockingBounds_set_local_blocking(self, *args)
    def get_arrival_blocking(self, *args): return _lp_analysis.BlockingBounds_get_arrival_blocking(self, *args)
    def set_arrival_blocking(self, *args): return _lp_analysis.BlockingBounds_set_arrival_blocking(self, *args)
    __swig_destroy__ = _lp_analysis.delete_BlockingBounds
    __del__ = lambda self : None;
BlockingBounds_swigregister = _lp_analysis.BlockingBounds_swigregister
BlockingBounds_swigregister(BlockingBounds)


def lp_dpcp_bounds(*args):
  return _lp_analysis.lp_dpcp_bounds(*args)
lp_dpcp_bounds = _lp_analysis.lp_dpcp_bounds

def lp_dflp_bounds(*args):
  return _lp_analysis.lp_dflp_bounds(*args)
lp_dflp_bounds = _lp_analysis.lp_dflp_bounds

def lp_mpcp_bounds(*args):
  return _lp_analysis.lp_mpcp_bounds(*args)
lp_mpcp_bounds = _lp_analysis.lp_mpcp_bounds

def lp_part_fmlp_bounds(*args):
  return _lp_analysis.lp_part_fmlp_bounds(*args)
lp_part_fmlp_bounds = _lp_analysis.lp_part_fmlp_bounds

def lp_omip_bounds(*args):
  return _lp_analysis.lp_omip_bounds(*args)
lp_omip_bounds = _lp_analysis.lp_omip_bounds

def lp_gfmlp_bounds(*args):
  return _lp_analysis.lp_gfmlp_bounds(*args)
lp_gfmlp_bounds = _lp_analysis.lp_gfmlp_bounds

def dummy_bounds(*args):
  return _lp_analysis.dummy_bounds(*args)
dummy_bounds = _lp_analysis.dummy_bounds

def lp_pfp_msrp_bounds(*args):
  return _lp_analysis.lp_pfp_msrp_bounds(*args)
lp_pfp_msrp_bounds = _lp_analysis.lp_pfp_msrp_bounds

def lp_pfp_preemptive_fifo_spinlock_bounds(*args):
  return _lp_analysis.lp_pfp_preemptive_fifo_spinlock_bounds(*args)
lp_pfp_preemptive_fifo_spinlock_bounds = _lp_analysis.lp_pfp_preemptive_fifo_spinlock_bounds

def lp_pfp_unordered_spinlock_bounds(*args):
  return _lp_analysis.lp_pfp_unordered_spinlock_bounds(*args)
lp_pfp_unordered_spinlock_bounds = _lp_analysis.lp_pfp_unordered_spinlock_bounds

def lp_pfp_baseline_spinlock_bounds(*args):
  return _lp_analysis.lp_pfp_baseline_spinlock_bounds(*args)
lp_pfp_baseline_spinlock_bounds = _lp_analysis.lp_pfp_baseline_spinlock_bounds

def lp_pfp_prio_spinlock_bounds(*args):
  return _lp_analysis.lp_pfp_prio_spinlock_bounds(*args)
lp_pfp_prio_spinlock_bounds = _lp_analysis.lp_pfp_prio_spinlock_bounds

def lp_pfp_prio_fifo_spinlock_bounds(*args):
  return _lp_analysis.lp_pfp_prio_fifo_spinlock_bounds(*args)
lp_pfp_prio_fifo_spinlock_bounds = _lp_analysis.lp_pfp_prio_fifo_spinlock_bounds

def lp_global_pip_bounds(*args):
  return _lp_analysis.lp_global_pip_bounds(*args)
lp_global_pip_bounds = _lp_analysis.lp_global_pip_bounds

def lp_ppcp_bounds(*args):
  return _lp_analysis.lp_ppcp_bounds(*args)
lp_ppcp_bounds = _lp_analysis.lp_ppcp_bounds

def lp_sa_gfmlp_bounds(*args):
  return _lp_analysis.lp_sa_gfmlp_bounds(*args)
lp_sa_gfmlp_bounds = _lp_analysis.lp_sa_gfmlp_bounds

def lp_global_fmlpp_bounds(*args):
  return _lp_analysis.lp_global_fmlpp_bounds(*args)
lp_global_fmlpp_bounds = _lp_analysis.lp_global_fmlpp_bounds

def lp_prsb_bounds(*args):
  return _lp_analysis.lp_prsb_bounds(*args)
lp_prsb_bounds = _lp_analysis.lp_prsb_bounds

def lp_no_progress_fifo_bounds(*args):
  return _lp_analysis.lp_no_progress_fifo_bounds(*args)
lp_no_progress_fifo_bounds = _lp_analysis.lp_no_progress_fifo_bounds

def lp_no_progress_priority_bounds(*args):
  return _lp_analysis.lp_no_progress_priority_bounds(*args)
lp_no_progress_priority_bounds = _lp_analysis.lp_no_progress_priority_bounds
# This file is compatible with both classic and new-style classes.


