# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_sim', [dirname(__file__)])
        except ImportError:
            import _sim
            return _sim
        if fp is not None:
            try:
                _mod = imp.load_module('_sim', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _sim = swig_import_helper()
    del swig_import_helper
else:
    import _sim
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Task(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Task, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Task, name)
    __repr__ = _swig_repr
    def init(self, *args): return _sim.Task_init(self, *args)
    def __init__(self, wcet=0, period=0, deadline=0, prio_pt=0, susp=0, max_tardiness=0): 
        this = _sim.new_Task(wcet, period, deadline, prio_pt, susp, max_tardiness)
        try: self.this.append(this)
        except: self.this = this
    def get_period(self): return _sim.Task_get_period(self)
    def get_wcet(self): return _sim.Task_get_wcet(self)
    def get_deadline(self): return _sim.Task_get_deadline(self)
    def get_prio_pt(self): return _sim.Task_get_prio_pt(self)
    def get_self_suspension(self): return _sim.Task_get_self_suspension(self)
    def get_tardiness_threshold(self): return _sim.Task_get_tardiness_threshold(self)
    def has_implicit_deadline(self): return _sim.Task_has_implicit_deadline(self)
    def has_constrained_deadline(self): return _sim.Task_has_constrained_deadline(self)
    def is_feasible(self): return _sim.Task_is_feasible(self)
    def is_self_suspending(self): return _sim.Task_is_self_suspending(self)
    def bound_demand(self, *args): return _sim.Task_bound_demand(self, *args)
    def dbf(self, *args): return _sim.Task_dbf(self, *args)
    def approx_load(self, *args): return _sim.Task_approx_load(self, *args)
    __swig_destroy__ = _sim.delete_Task
    __del__ = lambda self : None;
Task_swigregister = _sim.Task_swigregister
Task_swigregister(Task)

class TaskSet(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TaskSet, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TaskSet, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _sim.new_TaskSet(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sim.delete_TaskSet
    __del__ = lambda self : None;
    def add_task(self, *args): return _sim.TaskSet_add_task(self, *args)
    def get_task_count(self): return _sim.TaskSet_get_task_count(self)
    def has_only_implicit_deadlines(self): return _sim.TaskSet_has_only_implicit_deadlines(self)
    def has_only_constrained_deadlines(self): return _sim.TaskSet_has_only_constrained_deadlines(self)
    def has_only_feasible_tasks(self): return _sim.TaskSet_has_only_feasible_tasks(self)
    def has_no_self_suspending_tasks(self): return _sim.TaskSet_has_no_self_suspending_tasks(self)
    def is_not_overutilized(self, *args): return _sim.TaskSet_is_not_overutilized(self, *args)
    def bound_demand(self, *args): return _sim.TaskSet_bound_demand(self, *args)
    def get_period(self, *args): return _sim.TaskSet_get_period(self, *args)
    def get_wcet(self, *args): return _sim.TaskSet_get_wcet(self, *args)
    def get_deadline(self, *args): return _sim.TaskSet_get_deadline(self, *args)
TaskSet_swigregister = _sim.TaskSet_swigregister
TaskSet_swigregister(TaskSet)

class Stats(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Stats, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Stats, name)
    __repr__ = _swig_repr
    __swig_setmethods__["num_tardy_jobs"] = _sim.Stats_num_tardy_jobs_set
    __swig_getmethods__["num_tardy_jobs"] = _sim.Stats_num_tardy_jobs_get
    if _newclass:num_tardy_jobs = _swig_property(_sim.Stats_num_tardy_jobs_get, _sim.Stats_num_tardy_jobs_set)
    __swig_setmethods__["num_ok_jobs"] = _sim.Stats_num_ok_jobs_set
    __swig_getmethods__["num_ok_jobs"] = _sim.Stats_num_ok_jobs_get
    if _newclass:num_ok_jobs = _swig_property(_sim.Stats_num_ok_jobs_get, _sim.Stats_num_ok_jobs_set)
    __swig_setmethods__["total_tardiness"] = _sim.Stats_total_tardiness_set
    __swig_getmethods__["total_tardiness"] = _sim.Stats_total_tardiness_get
    if _newclass:total_tardiness = _swig_property(_sim.Stats_total_tardiness_get, _sim.Stats_total_tardiness_set)
    __swig_setmethods__["max_tardiness"] = _sim.Stats_max_tardiness_set
    __swig_getmethods__["max_tardiness"] = _sim.Stats_max_tardiness_get
    if _newclass:max_tardiness = _swig_property(_sim.Stats_max_tardiness_get, _sim.Stats_max_tardiness_set)
    __swig_setmethods__["first_miss"] = _sim.Stats_first_miss_set
    __swig_getmethods__["first_miss"] = _sim.Stats_first_miss_get
    if _newclass:first_miss = _swig_property(_sim.Stats_first_miss_get, _sim.Stats_first_miss_set)
    def __init__(self): 
        this = _sim.new_Stats()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _sim.delete_Stats
    __del__ = lambda self : None;
Stats_swigregister = _sim.Stats_swigregister
Stats_swigregister(Stats)


def edf_misses_deadline(*args):
  return _sim.edf_misses_deadline(*args)
edf_misses_deadline = _sim.edf_misses_deadline

def edf_first_violation(*args):
  return _sim.edf_first_violation(*args)
edf_first_violation = _sim.edf_first_violation

def edf_observe_tardiness(*args):
  return _sim.edf_observe_tardiness(*args)
edf_observe_tardiness = _sim.edf_observe_tardiness
# This file is compatible with both classic and new-style classes.


